services:
  - type: web
    name: neomed-website
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    # routes:
    #   - type: rewrite
    #     source: /*
    #     destination: /index.html
    routes:
      - type: rewrite
        source: /coming-soon
        destination: /coming-soon.html
      - type: redirect
        source: /*
        destination: /coming-soon
