services:
  - type: web
    name: neomed-website
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /admin/*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
